algoritmo "semnome"
// Função :
// Autor :
// Data : 07/10/2022
// Seção de Declarações 
var

tempCelcius, tempFaren: real


inicio

Escreval ("Vamos converter Celcius para Farenhait!")
Escreva ("Qual a temperatura atual (em Celcius)? ")
Leia (tempCelcius)
tempFaren <- tempCelcius * 9 / 5 + 32
Escreva ("Na escala Farenheit, a temperatura atual é", tempFaren,"ºF!")




fimalgoritmo
