algoritmo "CambioDolar"
// Função :
// Autor :
// Data : 07/10/2022
// Seção de Declarações 
var

valorReais, cotacaoDolar, valorDolares: real

inicio

Escreva ("Vamos fazer um câmbio? Que valor tens em reais? ")
Leia (valorReais)
Escreva ("Qual a cotação do dolar: ")
Leia (cotacaoDolar)
valorDolares <- valorReais / cotacaoDolar
Escreval ("Tens o equivalente a US$ ",valorDolares:2:2)




fimalgoritmo
