algoritmo "Desconto"
// Função :
// Autor :
// Data : 07/10/2022
// Seção de Declarações 
var

preco, desconto, valorFinal: real

inicio

Escreva ("Chê, qual o valor do bagulho que tu quer comprar? ")
Leia (preco)
Escreva ("E quanto por cento queres de desconto? ")
Leia (desconto)
valorFinal <- preco *(100 - desconto) / 100
Escreval ("Se conseguires esses", desconto, "% de desconto, vais pagar só R$",valorFinal,"!")



fimalgoritmo
